### Site info:
title: JavaScript Manual
author: Brett Taylor
email: brett.taylor@yoobee.ac.nz

### Site setting:
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

### Build settings
highlighter: pygments
paginate: 5
markdown: redcarpet